version: "3.3"
services:

  # cluster-level mongoDB
  mongo_clusternet:
    image: mongo:3.6
    container_name: cluster_mongo_net
    hostname: cluster_mongo_net
    ports:
      - "10108:10108"
    volumes:
      - 'mongodb_cluster_net_data:/mongodb'
    command: mongod --port 10108


# Cluster Manager
  cluster_service_manager:
    image: cluster_service_manager
    build: service-manager/
    container_name: cluster_service_manager
    hostname: cluster_service_manager
    expose:
      - "10110"
    ports:
      - "10110:10110"
    environment:
      - MY_PORT=10110
      - MQTT_BROKER_PORT=10003
      - MQTT_BROKER_URL=mqtt
      - ROOT_SERVICE_MANAGER_URL=${SYSTEM_MANAGER_URL}
      - ROOT_SERVICE_MANAGER_PORT=10099
      - SYSTEM_MANAGER_URL=cluster_manager
      - SYSTEM_MANAGER_PORT=10000
      - CLUSTER_MONGO_URL=cluster_mongo_net
      - CLUSTER_MONGO_PORT=10108
    depends_on:
      - mongo_clusternet
      - mqtt

volumes:
  mongodb_cluster_net_data:
    driver: local

networks:
  default:
    external:
      name: clusterorchestrator_default